# function to create a user for database. 
# Use '_id' to reference field generated by MongoDB
def userEntity(item) -> dict:
    return {
        "id": str(item["_id"]),    
        "name": item["name"],
        "email": item["email"],
        "password": item["password"]
    }

# function to return a list of all users in the database.
def usersEntity(entity) -> list:
    return [userEntity(item) for item in entity]
